[build-system]
requires = ["setuptools>=68.1.2"]
build-backend = "setuptools.build_meta"

[project]
name = "finra-py"
version = "1.1.0"
authors = [
	{name = "Hawk Berry", email = "finra@hawkberry.com"},
	]
description = "An Unofficial, Open-Source Python Client Library for the FINRA API Platform"
readme = "README.rst"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Office/Business :: Financial",
    "Topic :: Office/Business :: Financial :: Investment",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
	]
license = "MIT"
license-files = ["LICENSE"]
keywords = [
	"finra", "finra-api", "api-client", "rest-api", "market-data", "compliance", "regulatory", "regtech", "broker-dealer", "trading", "fixed-income", "short-interest", "trace",
	]
dependencies = [
    "authlib",
    "httpx",
    "jsonschema",
    "tzdata",
	]

[project.optional-dependencies]
docs = [
	"sphinx==9.1.0",
	"sphinx-autodoc-typehints==3.6.3",
	"pydata-sphinx-theme==0.19.0",
	]
lint = [
	"ruff==0.15.2",
	]
stats = [
	"pycodestats",
	]
test = [
    "colorama==0.4.6",
    "coverage==7.14.2",
	]
tox = [
	"tox==4.49.1",
	]
types = [
	"mypy==1.19.1",
	"types-Authlib==1.6.8.20260215",
	"types-colorama==0.4.15.20260508",
	"types-jsonschema==4.26.0.20260518",
	]
dev = [
	"finra-py[docs,lint,stats,test,tox,types]",
	]

[project.urls]
Documentation = "https://finra.hawkberry.com/"
Repository = "https://github.com/hawkberry/finra-py"
Changelog = "https://github.com/hawkberry/finra-py/blob/main/CHANGELOG.md"
Consulting = "https://finra.hawkberry.com/en/latest/consulting.html"
Support = "https://support.hawkberry.com/"
Issues = "https://github.com/hawkberry/finra-py/issues"

[tool.coverage.paths]
source = [
    "finra",
    "*/finra",
    "*\\finra",
	]

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"raise NotImplementedError",
	]

[tool.coverage.run]
branch = true

[tool.finra-py]
license_url = "https://github.com/hawkberry/finra-py/blob/main/LICENSE"
pypi_url = "https://pypi.org/project/finra-py/"

[[tool.mypy.overrides]]
module = "referencing"
ignore_errors = true

[tool.setuptools.packages.find]
where = ["."]
include = [
	"finra",
	"finra.filings",
	]

