[tox]
requires = tox>=4
env_list = py311, py312, py313, py314, ruff, mypy, coverage

[testenv]
description = run coverage unittest
deps = .[test]
allowlist_externals=coverage
commands = 
	coverage run --rcfile=pyproject.toml --source=finra --branch -p -m unittest discover -s tests -t . -p "test*.py"

[testenv:ruff]
description = run ruff linter
deps = .[lint]
commands = ruff check finra tests

[testenv:mypy]
description = run mypy type checker
deps = .[types]
commands = mypy finra tests

[testenv:coverage]
description = build coverage report
skip_install = true
commands =
    coverage combine --rcfile=pyproject.toml
    coverage report --rcfile=pyproject.toml
    coverage xml --rcfile=pyproject.toml
    coverage html --rcfile=pyproject.toml
