name: release

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build distribution

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: python3 -m pip install build

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v6
        with:
          name: python-package-distributions
          path: dist/

  testpypi:
    name: Publish to TestPyPI

    needs:
      - build

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/finra-py  # REPLACE: <package-name>

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  pypi:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    needs:
      - build
      - testpypi

    environment:
      name: pypi
      url: https://pypi.org/p/finra-py  # REPLACE: <package-name>

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

